### ISSUE TITLE
Wrong URLs for Recursive pages/paths

### ISSUE THREAD

**Issue by shubhamagarwal92** [jerpint/buster#126]
It seems that the `docparser` generates wrong URLs for recursive paths, ignoring the directory structure. 

Simple fix could be:  
1. Define `filename` in `get_document` [here](https://github.com/jerpint/buster/blob/main/buster/docparser.py#L51) and use `filename` instead of deriving `filename = Path(filepath).name` [here](https://github.com/jerpint/buster/blob/main/buster/docparser.py#L66)

2. Pass `file` while calling `get_document` in `get_all_documents` [here](https://github.com/jerpint/buster/blob/main/buster/docparser.py#L101)

Please let me know if this makes sense. I can raise a quick PR :)

**Comment by jerpint** [comment]
Hey thanks for the issue! I actually just opened a PR for this in #125, should be merged soon and fix the issue you can use that branch for now if you want to quickly get started

**Comment by jerpint** [comment]
Closing as this was fixed
