### ISSUE TITLE
Adaptability to any specific data

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [jerpint/buster#34]
Hi,

Thanks for this great repo!

Is this code adaptable to any website or are there any specific format to work fine?

Would it work with .pdf file with some little rework?

**Comment by jerpint** [comment]
Hey @Matthieu-Tinycoaching !

Currently we have two examples of deployment on the repo, one as a slackbot, and one as a gradio app (like the huggingface space) https://github.com/jerpint/buster/tree/main/buster/apps.

However, most of the code is wrapped up neatly as a python API so you could deploy this easily as a backend and hook it up to a website.

As for PDFs, parsing PDFs can be pretty challenging depending on their format. As long as you are able to extract the plaintext, in theory, it could work! Right now we only have support for scraping html websites using beautifulsoup.
