### ISSUE TITLE
Gradio version 

### ISSUE THREAD

**Issue by AlonEfrati** [jerpint/buster#52]
Gradio has been updated to 3.19 which is not compatible with the current setup. Should add "gradio" to requirements.txt and force the version tp 3.18.

**Comment by jerpint** [comment]
Hey @AlonEfrati I just installed the latest version of gradio (3.19.1), and the app seems to work fine without changing anything, what exactly isn't working for you?

**Comment by jerpint** [comment]
Note also that gradio is not a requirement of the project and is not in `requirements.txt` so you can install whatever version you want
