### ISSUE TITLE
Dataset format

### ISSUE THREAD

**Issue by iy-singh** [jerpint/buster#72]
This is a great repo. Amazing work !! 
I was wondering how can I use csv or txt file and not a tar.gz file? 

Thank you and regards
Ishmeet

**Comment by jerpint** [comment]
Thanks! we will look into making a better tutorial for getting started, but in theory all of our methods should handle `.csv` just as well as `.tar.gz`, the only reason we used `.tar.gz` was that the embeddings make csvs impractical storage wise
